### ISSUE TITLE
Implement development environment for a frontend part

### ISSUE THREAD

**Issue by Lehersun** [skbu3u/web-interface#1]
1. Create react-js blank project

**Comment by Lehersun** [comment]
What do you think about using https://bootstrap5.ru/ in this project?

**Comment by xansochi** [comment]
In fact, it's the same thing. Bootstrap already has a library of built-in interface elements, such as a button, a drop-down list, and so on. But because of this, all the elements look flat and the same.
All Bootstrap projects look similar. If you need to design any new element, go ahead in CSS.

There are no ready-made components in Tailwind, you can do each button yourself. It's harder, but in the end the interface turns out to be more beautiful. In production Tailwind use PurgeCSS utility, that keep only the CSS that realy used.

Bootstrap dev example 

`<button class=”btn btn-primary”>Awesome Button</button>`

Tailwind CSS dev example
 
`<button class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded"> Awesome Button </button>`

As you can see, tailwind looks more heavy in development because it does not use ready-made components, but in production CSS file be smaller in Tailwind, because this  - https://purgecss.com

There s milions comparison Bootstrap and Tailwind and Materialize and Ant and Chakra or another CSS in google.

**Comment by Lehersun** [comment]
I agree, let's try Tailwind. So what about creating blank React dev environment?
